import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/organisms/Footer";
import { GeneralHeader } from "../components/organisms/GeneralHeader";
import { HorizontalDevider } from "../components/atoms/HorizontalDevider";
import styles from "../styles/Home.module.css";
import { Hero } from "../components/organisms/Hero";
import { BlogSection } from "../components/organisms/BlogSection";
import { PortfolioSection } from "../components/organisms/PortfolioSection";
import { GitHubSection } from "../components/organisms/GitHubSection";
import { TwitterSection } from "../components/organisms/TwitterSection";
import { Grid } from "@mantine/core";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GeneralHeader links={[]} />

      <Hero />

      <main className={styles.main}>
        <Grid grow>
          <Grid.Col span={4}>1</Grid.Col>
          <Grid.Col span={4}>2</Grid.Col>
          <Grid.Col span={4}>3</Grid.Col>
          <Grid.Col span={4}>4</Grid.Col>
          <Grid.Col span={4}>5</Grid.Col>
        </Grid>
        <BlogSection />
        <PortfolioSection />
        <GitHubSection />
        <TwitterSection />

        <HorizontalDevider />
      </main>

      <Footer links={[]} />
    </div>
  );
};

export default Home;
