import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/organisms/Footer";
import { GeneralHeader } from "../components/organisms/GeneralHeader";
import { HorizontalDevider } from "../components/atoms/HorizontalDevider";
import styles from "../styles/Home.module.css";
import { Hero } from "../components/organisms/Hero";
import { BlogSection } from "../components/organisms/BlogSection";
import { PortfolioSection } from "../components/organisms/PortfolioSection";
import { GitHubSection } from "../components/organisms/GitHubSection";
import { TwitterSection } from "../components/organisms/TwitterSection";
import { Grid } from "@mantine/core";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GeneralHeader links={[]} />

      <Hero />

      <main className={styles.main}>
        {/* レイアウト変更に対応しやすくする目的で全セクションをグリッドで */}
        <Grid grow>
          <Grid.Col lg={12} md={12}>
            <BlogSection />
          </Grid.Col>
          <Grid.Col lg={12} md={12}>
            <PortfolioSection />
          </Grid.Col>
          <Grid.Col lg={12} md={6}>
            <GitHubSection />
          </Grid.Col>
          <Grid.Col lg={12} md={6}>
            <TwitterSection />
          </Grid.Col>
        </Grid>

        <HorizontalDevider />
      </main>

      <Footer links={[]} />
    </div>
  );
};

export default Home;
